---
- hosts: all
  become: yes

  pre_tasks:
  - name: Update apt cache if needed
    apt: update_cache=yes cache_valid=3600

  - name: "Install git"
    apt: 
      state: present
      name: git
  
  - name: "Clone repository"
    git:
      repo: https://github.com/ReaganCn/yolo.git
      dest: /opt/yolo
      clone: yes
      update: yes
  
  - name: "Create custom docker bridge network"
    docker_network:
      name: custom-network 
      driver: bridge
      ipam_config:
        subnet: "192.168.128.0/24"
        gateway: "192.168.128.1"
      ipam_driver: default

      

  - name: "Create volume to use for persisting database"
    docker_volume:
      name: backend-mongodb

  
  roles:
    - client
    - backend
    - mongodb
